### ISSUE TITLE
[Request] Add the file uploading feature from henkelmax's Audio Player.

### ISSUE THREAD

**Issue by IzMichael** [Navoei/CustomDiscs#1]
I'd love for my players to be able to upload their own `.wav` files with a command, instead of having to upload it to the server files.

**Comment by Navoei** [comment]
So something like ```/songdownload``` ? Doesnt seem that hard, but currently im working on support for mp3 files, then ill get to that. 
Thank you for the suggestion!

**Comment by MoodTheCoolDude** [comment]
I would probably make the command be something like /cd upload instead for better organization.

**Comment by Navoei** [comment]
Yeah I will rework the syntax after the mp3 support update. 
I will be adding file uploads as well as a speaker system.

**Comment by IzMichael** [comment]
For speakers, could you not just add a feature that lets you play music discs in a jukebox with a hopper?

**Comment by Navoei** [comment]
True, i could do that actually...

**Comment by viperlife** [comment]
Bump, anything happening with this in the near future?

**Comment by Navoei** [comment]
Ive never done anything with file uploading, so this is quite new to me. Im currently trying to find a good way to do this.

**Comment by IzMichael** [comment]
It's ok!

The way I've seen it being done before, is to request users to upload the file to filebin or a similar service, and then take the filebin link as a command parameter...

**Comment by Navoei** [comment]
So Ive been reading up on this and it is out of my scope of knowledge right now. Though I know all of the basics of Java and can code plugins like this for Bukkit, I have no idea how the file uploading works. Furthermore, I will be heading back to school tomorrow, and although I hope it doesnt take time off of continuing to support this project, I wont have much time to learn new things. I do take a Java programming class in school, but we have not gotten that far in our course.

**Comment by Navoei** [comment]
Sorry if this dissapoints any of you :(

**Comment by Th3UnknownCoder** [comment]
I can fork and add the file uploading if you want, you just may want to go over it and clean it up after @Navoei. I don't do a lot of Java but ive done it for a different project.

**Comment by Navoei** [comment]
Of coarse! I will greatly appreciate it if you can contribute. I will also credit you in the comments of the code and in the readme as well.

**Comment by ChillBrian** [comment]
so how is this going? If u don't mind me asking

**Comment by DaCringyLemon** [comment]
any progress?

**Comment by Navoei** [comment]
Currently I am working on another project for my Computer Science class which uses google drive to manage playlists
I can use the knowledge i gain from that project and apply it here.
The only problem is that the project, along with my other classes, take up a lot of my time.

**Comment by Navoei** [comment]
I'm sorry for not keeping up to date with this project. It has been a long time but it seems like a developer forked this plugin to add file uploading: [https://github.com/NotGeri/CustomDiscs](https://github.com/NotGeri/CustomDiscs) .

If they were to make a pull request I may implement it.

**Comment by Navoei** [comment]
Currently working on this right now.

**Comment by Navoei** [comment]
Version 2.3 is now released:

https://github.com/Navoei/CustomDiscs/releases/tag/Latest
