### ISSUE TITLE
[Request] add redstone signal support for skip discs

### ISSUE THREAD

**Issue by maxsspeaker** [Navoei/CustomDiscs#10]
please make it so that when a redstone signal is given, the music player skips the track and ejects the disc / transfers it to the dropper
this will help a lot in the build of various musical mechanisms..

**Comment by Navoei** [comment]
This seems really awesome, ill try to do it :)

**Comment by Navoei** [comment]
I can do something where the disc is sent to the hopper when a redstone signal is sent to the jukebox. 
This is taking a while as I am very busy with school.

**Comment by antillagorilla** [comment]
I feel like this isn't really necessary, as you can have a hopper underneath the jukebox, and have it powered until you want the disc to be taken out. So with a redstone torch inverter, you could have it "skip" the disc out of the jukebox into the hopper underneath.

**Comment by Navoei** [comment]
The discs in this plugin behave similarly to bedrock's
The disc will stay in the jukebox until the track finishes, then the disc comes out

**Comment by antillagorilla** [comment]
Oh. Upon checking, you are indeed correct (which would make sense considering you made the thing). I could swear it just took the disc out, and I built a whole like redstone circuit thing to make something function. But I guess I didn't ever try it that simple, and I just assumed it would work like the similar fabric mod. Thanks for letting me know!
