### ISSUE TITLE
New Config File Option

### ISSUE THREAD

**Issue by The12thUnique** [Navoei/CustomDiscs#13]
I noticed something and wonder if it can be slightly changed - 

V2.1.1 - Jukebox would give a redstone output of 15 regardless of what type of disc was being played(yellow, green, etc)
I update to...
V2.2.2 - Jukebox redstone output is now dependent on what type of disc is being played. 

Now I welcome the change as I can see how it could be useful however as I pondered over it and changed my music machine to accommodate it I wondered whether it would be possible to have a toggle/option for this in the config file?

**Comment by Navoei** [comment]
To be honest, all u need to do is add a repeater after the comparator to strengthen the signal to 15 regardless of what disc is in the jukebox.

**Comment by The12thUnique** [comment]
I know I have done that, as I said in the original comment I just wondered if this behavior could be made toggleable.

**Comment by Navoei** [comment]
hmmm idk about that, messing with redstone using bukkit is wierd...
