### ISSUE TITLE
[Request] Support for Folders

### ISSUE THREAD

**Issue by CastedShadow** [Navoei/CustomDiscs#14]
Having support for folders would be a huge help for organizing audio files!

**Comment by Navoei** [comment]
seems like a good idea! perhaps i will change the create command to require a folder name
development is slow because im in school but once break comes i will work on this plugin again :D

**Comment by Navoei** [comment]
Folders do work in the plugin
All you have to do is specificy a filepath
For example:
```/cd create /YourFolder/song.mp3 "My custom disc :)"```
