### ISSUE TITLE
Broken on 1.19.2 Paper

### ISSUE THREAD

**Issue by aleabodo** [Navoei/CustomDiscs#19]
The plugin is loaded without any issues. For some reason it plays the Vanilla disc instead of the custom one. I haven't changed anything except update the server from 1.19 to 1.19.2 and update the voice chat plugin and Custom Discs plugin. I made sure all mp3s are in their place and the disc is created properly. No other player can hear the music too.

**Comment by Navoei** [comment]
If you updated the plugin, some discs may need to be converted to a new format. Use /cd convert.

**Comment by aleabodo** [comment]
Thanks, that made it work. I totally missed that. I'd suggest have this documented a bit better. I'd also suggest to not change the format too often in the future. These discs are an essential feature on our server and players find it annoying having convert all their discs, which amounts to multiple shulkers for some players.
