### ISSUE TITLE
The server does not see the plugin

### ISSUE THREAD

**Issue by Vadokk** [Navoei/CustomDiscs#21]
Hello!  I had a problem: I reinstalled all plugins on the server and removed this one.  When I installed it again - the server just stopped seeing it!  And even the other server does not see!  What could be the problem?

**Comment by Navoei** [comment]
This is a plugin for Paper servers.

**Comment by Vadokk** [comment]
> Это плагин для серверов Paper. Возможно, вы запускаете его на другом серверном программном обеспечении?

No, paper 1.19.2 But now I think I understand why it doesn't work!  thanks for the help!
