### ISSUE TITLE
/songdownload

### ISSUE THREAD

**Issue by Vadokk** [Navoei/CustomDiscs#22]
Cool plugin!  But still it would be cool if players could upload music themselves. I know this has been suggested before, but how is the progress?

**Comment by BaxAndrei** [comment]
BUMP!

**Comment by Navoei** [comment]
This is currently being worked on :)

**Comment by Navoei** [comment]
when using the create command, you can specify a url like this:
`/cd create "Disc Name" directory/songfile.mp3`
Keep in mind that the directory must be a folder inside the musicdata folder.

**Comment by Navoei** [comment]
This is a duplicate of #1
