### ISSUE TITLE
Plugin shows up in and commands aswell, but doesn't convert discs due to error

### ISSUE THREAD

**Issue by Momentusm** [Navoei/CustomDiscs#24]
Okay so I installed the plugin and protocollib etc

when I do /customdisc or /cd the command shows up as a supported command
but when I follow the exact format shown in examples, it refuses to work

Error: 
https://pastebin.com/vKWc1kPU

help would be much appreciated heh

**Comment by Navoei** [comment]
This is because the plugin is being run on Spigot or Bukkit. CustomDiscs only works on PaperMC server software.

**Comment by Momentusm** [comment]
oh, well that's kinda confusing seeing as all the releases say "spigot/bukkit" but okay, thank you!
