### ISSUE TITLE
Error when starting the server

### ISSUE THREAD

**Issue by imparium-de** [Navoei/CustomDiscs#28]
Title says it all. Sometimes the error appears, sometimes not https://pastebin.com/ng24s5Ma

**Comment by Navoei** [comment]
That is indeed very odd. Once 1.20 releases, this plugin will have a major update.

**Comment by erxson** [comment]
Almost same error https://pastebin.com/ZFape86C

**Comment by erxson** [comment]
Every time, when player puts disc in jukebox

**Comment by Navoei** [comment]
Check to make sure you are using the latest voicechatplugin version.

**Comment by erxson** [comment]
2.2.3 from release page

**Comment by imparium-de** [comment]
> 2.2.3 from release page

Voicechat, not CustomDiscs

Seems like the newest version from CurseForge is 2.3.28
https://www.curseforge.com/minecraft/bukkit-plugins/simple-voice-chat/files/all
![image](https://user-images.githubusercontent.com/63745647/222983729-5e499462-e7d5-43d6-b424-70e7f0dd39d2.png)

**Comment by imparium-de** [comment]
> That is indeed very odd. Once 1.20 releases, this plugin will have a major update.

Do you have a rough estimate as to when 1.20 will be released? Our server is still in the works and we use the plugin for some minor atmospheric sounds so it's not a game breaker, but I had some other things that I wanted to test :D

**Comment by erxson** [comment]
Sorry, brainissue. 2.3.28 version is installed.

**Comment by Navoei** [comment]
A new version was released for version 1.19.4.
