### ISSUE TITLE
[Request] Volume control

### ISSUE THREAD

**Issue by aleabodo** [Navoei/CustomDiscs#3]
It would be amazing if the volume of the disc would be tied to the Jukebox volume settings. Alternatively I'd like to adjust the volume settings server-wide in a config file preferably.

The reason I'm suggesting this is because the discs are quiet loud by default. Much louder than normal discs or other sounds.

**Comment by Navoei** [comment]
Yeah i understand that. Ive had that issue too! That is totally possible. 
I'll add a new category under Adjust Player Volumes and make a server-side master volume.
This would be included in the next update. 

Thanks for your suggestion!
