### ISSUE TITLE
ERROR Could not pass event InventoryMoveItemEvent

### ISSUE THREAD

**Issue by CapNJunkie** [Navoei/CustomDiscs#31]
Paper 1.19.3, Voicechat-1.19.3-2.3.28
`01.04 12:02:26 [Server] ERROR Could not pass event InventoryMoveItemEvent to CustomDiscs v2.3
01.04 12:02:26 [Server] INFO java.lang.NoSuchFieldError: JUKEBOX
01.04 12:02:26 [Server] INFO at me.Navoei.customdiscsplugin.HopperManager.onJukeboxEjectToHopper(HopperManager.java:53) ~[custom-discs-2.3.jar:?]
01.04 12:02:26 [Server] INFO at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor97.execute(Unknown Source) ~[?:?]
01.04 12:02:26 [Server] INFO at org.bukkit.plugin.EventExecutor$2.execute(EventExecutor.java:77) ~[paper-api-1.19.3-R0.1-SNAPSHOT.jar:?]
01.04 12:02:26 [Server] INFO at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[paper-api-1.19.3-R0.1-SNAPSHOT.jar:git-Paper-396]
01.04 12:02:26 [Server] INFO at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[paper-api-1.19.3-R0.1-SNAPSHOT.jar:?]
01.04 12:02:26 [Server] INFO at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:672) ~[paper-api-1.19.3-R0.1-SNAPSHOT.jar:?]
01.04 12:02:26 [Server] INFO at org.bukkit.event.Event.callEvent(Event.java:45) ~[paper-api-1.19.3-R0.1-SNAPSHOT.jar:?]
01.04 12:02:26 [Server] INFO at net.minecraft.world.level.block.entity.HopperBlockEntity.callPushMoveEvent(HopperBlockEntity.java:284) ~[?:?]
01.04 12:02:26 [Server] INFO at net.minecraft.world.level.block.entity.HopperBlockEntity.hopperPush(HopperBlockEntity.java:213) ~[?:?]
01.04 12:02:26 [Server] INFO at net.minecraft.world.level.block.entity.HopperBlockEntity.ejectItems(HopperBlockEntity.java:355) ~[?:?]
01.04 12:02:26 [Server] INFO at net.minecraft.world.level.block.entity.HopperBlockEntity.tryMoveItems(HopperBlockEntity.java:158) ~[?:?]
01.04 12:02:26 [Server] INFO at net.minecraft.world.level.block.entity.HopperBlockEntity.pushItemsTick(HopperBlockEntity.java:139) ~[?:?]
01.04 12:02:26 [Server] INFO at net.minecraft.world.level.chunk.LevelChunk$BoundTickingBlockEntity.tick(LevelChunk.java:1304) ~[?:?]
01.04 12:02:26 [Server] INFO at net.minecraft.world.level.chunk.LevelChunk$RebindableTickingBlockEntityWrapper.tick(LevelChunk.java:1256) ~[?:?]
01.04 12:02:26 [Server] INFO at net.minecraft.world.level.Level.tickBlockEntities(Level.java:899) ~[?:?]
01.04 12:02:26 [Server] INFO at net.minecraft.server.level.ServerLevel.tick(ServerLevel.java:740) ~[?:?]
01.04 12:02:26 [Server] INFO at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1535) ~[paper-1.19.3.jar:git-Paper-396]
01.04 12:02:26 [Server] INFO at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:447) ~[paper-1.19.3.jar:git-Paper-396]
01.04 12:02:26 [Server] INFO at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1397) ~[paper-1.19.3.jar:git-Paper-396]
01.04 12:02:26 [Server] INFO at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1173) ~[paper-1.19.3.jar:git-Paper-396]
01.04 12:02:26 [Server] INFO at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:316) ~[paper-1.19.3.jar:git-Paper-396]
01.04 12:02:26 [Server] INFO at java.lang.Thread.run(Thread.java:833) ~[?:?]`

**Comment by Navoei** [comment]
The latest version is for 1.19.4

**Comment by CapNJunkie** [comment]
Oh? is the a 1.19.3 compatible version then? Thank you so much for your time.

**Comment by Navoei** [comment]
Yes, here is the link to the 1.19.3 version:

https://github.com/Navoei/CustomDiscs/releases/tag/v2.2.3

**Comment by CapNJunkie** [comment]
that's awesome, thank you. I saw that one, but it didn't say what version so I assumed since it was before 1.19.3 was released that it wasn't compatible.
I appreciate your help. <3
