### ISSUE TITLE
Releases name

### ISSUE THREAD

**Issue by BaxAndrei** [Navoei/CustomDiscs#32]
Can you please use the numbering as before for versions (1.2.3, 1.2.4, 1.3.. etc) instead of latest as you used for the last release? I have a script that automatically searches for plugin updates and since you put latest on the last release, it no longer displays correctly for this plugin, because script is waiting for a valid version higher than 2.2.3 (installed on server)

**Comment by Navoei** [comment]
Alright I'll do it

**Comment by Navoei** [comment]
I added a v2.3 tag, hopefully that fixes your issue.

**Comment by BaxAndrei** [comment]
Thank you!
