### ISSUE TITLE
versions 2.3 and above crash the server

### ISSUE THREAD

**Issue by Mikoyami** [Navoei/CustomDiscs#34]
customdiscs version 2.3 and above crash the server. the plugin just spams the console. at the same time it works, but when you insert a plate, the server's TPS drops to a low value and crashes the server. SimpleVoice is working normaly

Paper 1.19.3 
![image](https://user-images.githubusercontent.com/131993208/234921070-4823c446-54b9-49e8-b09d-445931c7a655.png)

**Comment by notqtcris** [comment]
Use Paper 1.19.4?

**Comment by notqtcris** [comment]
Newest build of paper
