### ISSUE TITLE
The Discs wont play and i'm getting errors in my console

### ISSUE THREAD

**Issue by alezhshede** [Navoei/CustomDiscs#36]
https://pastebin.com/mKKHtNWH I don't know if i've done anything wrong so i thought i'd ask here
Thanks in advance

**Comment by Navoei** [comment]
This might be due to the voice chat version. Attempt upgrading/downgrading to see if it fixes the issue. Currently I know that version 2.4.3 works.

**Comment by Navoei** [comment]
And by version I mean the plugin version, not your mod version.

**Comment by alezhshede** [comment]
voicechat-bukkit-2.4.3-pre1.jar
custom-discs-2.3.1.jar

These are the versions of the plugins
And i'm getting the exact same warn message

**Comment by Navoei** [comment]
In the error, it says voicechat-bukkit-1.19.4-2.4.2. I recommend updating your voice chat version. My current setup for using my plugin is exactly the same and I am not getting these errors. It could be the case that the audio file is currupted or the file format is incorrect as well.

**Comment by alezhshede** [comment]
I've tried the versions you suggested. and tried to update and downgrade,
i'm using mp3 as fileformt.

But ill try more files to see if that makes a difference
