### ISSUE TITLE
Update for new versions

### ISSUE THREAD

**Issue by LYNCHESSS** [Navoei/CustomDiscs#39]
Please update to 1.20, thanks in advance

**Comment by Navoei** [comment]
I am currently working on an update to 1.20.1. The only issue now is ProtocolLib might take a while to update.

**Comment by Navoei** [comment]
Looking into the releases of ProtocolLib it seems that one is out for 1.20, with support for 1.20.1.
https://ci.dmulloy2.net/job/ProtocolLib/651/
