### ISSUE TITLE
NullPointerException

### ISSUE THREAD

**Issue by Kriptiq** [Navoei/CustomDiscs#4]
Hi, I'm getting this error. https://pastebin.com/GS4Z2gXg
I don't know if it's because we are using Paper and it states bukkit/spigot you support? Or if plugin is not yet updated to 1.19.2? Or if I have something else going on?

**Comment by aleabodo** [comment]
I'm getting the same error pretty frequently. It'll spam many of them in quick succession. However, I cannot reliably reproduce it and don't know what's causing it. 

It does not seem to break anything. It's cluttering the server logs though.

**Comment by Navoei** [comment]
Hmmm that's odd, can yall send me what version of paper you are using? I cant seem to replicate the issue...

**Comment by Kriptiq** [comment]
[Tue 14:47:37 INFO ] This server is running Paper version git-Paper-130 (MC: 1.19.2) (Implementing API version 1.19.2-R0.1-SNAPSHOT) (Git: 4ba43fe)
You are running the latest version
Previous version: git-Paper-127 (MC: 1.19.2)```

**Comment by Navoei** [comment]
Thanks! I'll find a solution to this as it seems it's just a small part of the code that is causing this.

**Comment by Kriptiq** [comment]
Ok thank you.

**Comment by Navoei** [comment]
The issue should be fixed now. Console shouldnt be spammed anymore. Thanks for reporting the bug! If there is any other bugs feel free to open another issue. 

The version that fixes this issue has been released.
