### ISSUE TITLE
Getting CustomDiscs to work 1.20.1

### ISSUE THREAD

**Issue by SinistersGrin** [Navoei/CustomDiscs#42]
The plugin wont start, im sorry if its an issue on my side i tried what i could thing of
[customdiscs.txt](https://github.com/Navoei/CustomDiscs/files/11777817/customdiscs.txt)
Or
https://justpaste.it/a3y75

Server Version: 
This server is running Paper version git-Paper-32 (MC: 1.20.1) (Implementing API version 1.20.1-R0.1-SNAPSHOT) (Git: 3885666)
You are running the latest version

CustomDiscs Version: 2.4
Simple Voice Chat Version: voicechat-bukkit-2.4.10

**Comment by Navoei** [comment]
This plugin requires the use of the SimpleVoiceChat plugin.

**Comment by Navoei** [comment]
I forgot to add the depend line on the plugin. It should be fixed on the next release.

**Comment by SinistersGrin** [comment]
Much appreciated, thank you for the amazing add on, and your time

**Comment by Navoei** [comment]
The issue should now be fixed. A new version has been released.
