### ISSUE TITLE
When any group member makes a sound, the music sound will become noisy.

### ISSUE THREAD

**Issue by Taiyopen** [Navoei/CustomDiscs#5]
When I'm on the edge of the music box (16m), as soon as any group member makes a sound, the music sound will become noisy.

Using custom-discs-2.1.1.jar

Vedio:[Vedio](https://youtu.be/RCOHqruftUU)

**Comment by Navoei** [comment]
I'll forward this to the main developer of simple voice chat as this does not seem to be a bug on my part.

I will keep you updated so dont worry.

**Comment by Taiyopen** [comment]
Thank you bro.

I have reported to simple voice chat's official Server, but he say "Custom discs is not a plugin by us 
Please report it to the plugin developer".
So, I try to find you to help me

**Comment by Navoei** [comment]
Yeah that's cause they dont want to be bothered by other plugins' problems, although this issue is most likely not my fault.

**Comment by Navoei** [comment]
This might not be fixed as it is not my issue... idk what they will do. Ill be closing this as it is out of my control.
