### ISSUE TITLE
[Request] Change file name and read condition

### ISSUE THREAD

**Issue by JustJass** [Navoei/CustomDiscs#6]
Hi,

I'm using your plugin on my server, and I'm trying to make them seamless with other discs. This is not possible with the current system of having the file name as line 2 of lore.

It would be a lot better in my opinion to use the "CustomTags" minecraft provide in order to let server owner complete freedom over the lore if they want to customize it.

~~I would also recommend moving the condition to try and read discs from "hide enchants" to either "hide dyed" or "hide unbreakable", as they're not used on discs.~~

I just realize that using a custom tag would negate the need for any hide flags, you would simply need to check if the item has the specified custom tag.

Thanks in advance

**Comment by Navoei** [comment]
Oh yeah true, the thing is on my server, people can change the lore of items, which is why I added an extra layer of "security", for lack of a better word.

**Comment by Navoei** [comment]
I did some more research and found out that PersistentDataContainers can be used on items. I will use that instead.

**Comment by JustJass** [comment]
Thanks! I appreciate you took the time to do this change, it will definitely help making custom discs a lot more seamless on servers!
And for the additional security, it would either be check for the presence of a custom tag or use HIDE_UNBREAKABLE (in the chance a server owner would want to enchant a disc, unbreakable is not doing anything on discs). But I understand changing this might break servers who are already using them, so maybe add a check to see if the disc has either? (if not too complex)

The only reason why I got reminded of those custom tags is because i use MCStacker to make my give commands!

All in all, thanks for accepting my request, I won't put this request as closed, I'm letting you do that in case you want to add the hide_unbreakable tag as alternative to hide_enchants, but what I needed already got implemented!

**Comment by Navoei** [comment]
I can use persistent data containers on items and just check if the item has that instead of adding a custom tag on top of that.

**Comment by Navoei** [comment]
Also, I added a /cd convert command to convert discs from the old format to the new one.

**Comment by JustJass** [comment]
Great! Thanks again! Should I close the issue?

**Comment by Navoei** [comment]
Yeah I'll close it!
