### ISSUE TITLE
The file must have an extension of wav, flac, or mp3

### ISSUE THREAD

**Issue by Timtaran** [Navoei/CustomDiscs#60]
Um... I tryed flac and mp3 and I'm getting this error

**Comment by Timtaran** [comment]
I reopened it because there is issue in readme

it says

`/cd download https://example.com/mysong "mysong.mp3"`

but it should be 
`/cd download https://example.com/mysong mysong.mp3`

**Comment by Navoei** [comment]
Oh thanks! I must have overlooked that. I'll fix it soon.
