### ISSUE TITLE
An error has occured while trying to play this disc.

### ISSUE THREAD

**Issue by niqeisw** [Navoei/CustomDiscs#63]
Hello, I have encountered an issue where discs do not play in the game if I assign them a file downloaded via the /cd download command. After downloading the file, I create a disc with it, but when I insert it into the player, I get the message in the chat: "An error has occurred while trying to play this disc." I decided to check the files downloaded directly through the command and found that they do not play even in Windows players, and they also cannot be added to Adobe Premiere Pro.

However, when I manually added my file to the folder, it worked perfectly in the game, and the disc played the custom music. How can I fix this issue?
(version: Purpur 1.20.4)
![git](https://github.com/Navoei/CustomDiscs/assets/169541882/31d8f219-4516-4cd9-a64a-83fb852b1629)

**Comment by Navoei** [comment]
Depends on the file extension. It could be that it is incorrect. Ensure the file extension is correct for the file being played. For example, you cannot play an mp3 file when it has to wav format.
